//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bozhong_dbEntities : DbContext
    {
        public bozhong_dbEntities()
            : base("name=bozhong_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bz_game_game_friend> bz_game_game_friend { get; set; }
        public virtual DbSet<game_config_award> game_config_award { get; set; }
        public virtual DbSet<game_config_change_gold> game_config_change_gold { get; set; }
        public virtual DbSet<game_config_email> game_config_email { get; set; }
        public virtual DbSet<game_config_product> game_config_product { get; set; }
        public virtual DbSet<game_config_robot_info> game_config_robot_info { get; set; }
        public virtual DbSet<game_config_room> game_config_room { get; set; }
        public virtual DbSet<game_config_route> game_config_route { get; set; }
        public virtual DbSet<game_config_test_game> game_config_test_game { get; set; }
        public virtual DbSet<game_game_friend> game_game_friend { get; set; }
        public virtual DbSet<game_game_score_change> game_game_score_change { get; set; }
        public virtual DbSet<game_user_account> game_user_account { get; set; }
        public virtual DbSet<game_user_address> game_user_address { get; set; }
        public virtual DbSet<game_user_player> game_user_player { get; set; }
        public virtual DbSet<game_version_config> game_version_config { get; set; }
        public virtual DbSet<log_create_table> log_create_table { get; set; }
        public virtual DbSet<log_friend_game_every_score> log_friend_game_every_score { get; set; }
        public virtual DbSet<log_friend_game_over> log_friend_game_over { get; set; }
        public virtual DbSet<log_friend_game_score> log_friend_game_score { get; set; }
        public virtual DbSet<log_game_order> log_game_order { get; set; }
        public virtual DbSet<log_game_play_over> log_game_play_over { get; set; }
        public virtual DbSet<log_game_server_uid> log_game_server_uid { get; set; }
        public virtual DbSet<log_game_share_friend> log_game_share_friend { get; set; }
        public virtual DbSet<log_gamelogin> log_gamelogin { get; set; }
        public virtual DbSet<log_gamelogout> log_gamelogout { get; set; }
        public virtual DbSet<log_ingot_detail> log_ingot_detail { get; set; }
    }
}
