//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bz_game_game_friend
    {
        public Nullable<int> UserID { get; set; }
        public Nullable<int> gameid { get; set; }
        public string game_rule { get; set; }
        public string room_code { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> roomid { get; set; }
        public Nullable<int> propid { get; set; }
        public Nullable<int> propcount { get; set; }
        public Nullable<int> kind { get; set; }
        public Nullable<int> totalcount { get; set; }
        public Nullable<int> currcount { get; set; }
        public Nullable<int> tallykind { get; set; }
        public string tallyname { get; set; }
        public string nickname { get; set; }
        public Nullable<int> follow_gold { get; set; }
        public Nullable<int> end_time { get; set; }
        public string game_address { get; set; }
        public Nullable<int> game_port { get; set; }
        public Nullable<int> game_play_type { get; set; }
    }
}
