//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_user_account
    {
        public int UserID { get; set; }
        public string Accounts { get; set; }
        public string LogonPass { get; set; }
        public string InsurePass { get; set; }
        public string nick_name { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string RegisterMachine { get; set; }
        public string WechatUid { get; set; }
        public Nullable<long> Gold { get; set; }
        public Nullable<long> Ingot { get; set; }
        public Nullable<int> clienttype { get; set; }
        public Nullable<int> client_area { get; set; }
        public Nullable<int> client_channel { get; set; }
        public Nullable<int> client_app { get; set; }
        public Nullable<int> client_version { get; set; }
        public Nullable<int> client_pkg { get; set; }
        public string keyword { get; set; }
        public string head_url { get; set; }
        public string wechat_unionid { get; set; }
        public Nullable<int> bind_number { get; set; }
    }
}
