//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_config_product
    {
        public int id { get; set; }
        public Nullable<int> kind_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<int> bind_buy_send { get; set; }
        public Nullable<int> product_num { get; set; }
        public string describe { get; set; }
        public string key_word { get; set; }
        public string product_id { get; set; }
    }
}
