//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_config_route
    {
        public int id { get; set; }
        public string game_address { get; set; }
        public Nullable<int> game_port { get; set; }
        public Nullable<int> kind_id { get; set; }
    }
}
