//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_config_award
    {
        public int id { get; set; }
        public string award_des { get; set; }
        public Nullable<int> ingot { get; set; }
        public Nullable<int> gold { get; set; }
    }
}
