//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_version_config
    {
        public int game_id { get; set; }
        public Nullable<int> min_ver { get; set; }
        public Nullable<int> cur_ver { get; set; }
        public Nullable<int> max_ver { get; set; }
        public Nullable<int> int_mask1 { get; set; }
        public Nullable<int> int_mask2 { get; set; }
        public Nullable<int> int_mask3 { get; set; }
        public string wechat_app_id { get; set; }
        public string wechat_app_secert { get; set; }
        public Nullable<int> login_mask1 { get; set; }
        public Nullable<int> login_mask2 { get; set; }
        public Nullable<int> login_mask3 { get; set; }
    }
}
