//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_game_score_change
    {
        public int UserID { get; set; }
        public Nullable<int> WinCount { get; set; }
        public Nullable<int> LostCount { get; set; }
        public Nullable<int> DrawCount { get; set; }
        public Nullable<int> FleeCount { get; set; }
        public Nullable<int> UserRight { get; set; }
        public Nullable<int> MasterRight { get; set; }
        public Nullable<int> PlayTimeCount { get; set; }
        public Nullable<int> AllLogonTimes { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public Nullable<int> LogonGold { get; set; }
        public Nullable<int> ChangeGold { get; set; }
        public Nullable<int> LastPlayTimeCount { get; set; }
        public Nullable<int> LastWinCount { get; set; }
        public Nullable<int> LastLostCount { get; set; }
        public Nullable<int> LastDrawCount { get; set; }
        public Nullable<int> LastScore { get; set; }
    }
}
