//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_config_robot_info
    {
        public int user_id { get; set; }
        public Nullable<int> kind { get; set; }
        public Nullable<int> server_id { get; set; }
        public Nullable<int> server_time { get; set; }
        public Nullable<int> min_play_draw { get; set; }
        public Nullable<int> max_play_draw { get; set; }
        public Nullable<int> min_repose_time { get; set; }
        public Nullable<int> max_repose_time { get; set; }
        public Nullable<int> server_gender { get; set; }
        public Nullable<int> min_score { get; set; }
        public Nullable<int> max_score { get; set; }
    }
}
