//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_game_order
    {
        public string order_id { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<decimal> order_money { get; set; }
        public Nullable<int> kind_id { get; set; }
        public Nullable<int> pay_type { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> channel { get; set; }
        public string product_id { get; set; }
        public string out_orderno { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public Nullable<decimal> pay_money { get; set; }
        public Nullable<decimal> real_money { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public int ingot_num { get; set; }
    }
}
