//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_ingot_detail
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public Nullable<int> ingot_num { get; set; }
        public Nullable<int> kind_id { get; set; }
        public Nullable<int> reason { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> channel { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> source_id { get; set; }
        public Nullable<long> after_ingot { get; set; }
        public Nullable<long> before_ingot { get; set; }
        public string remark { get; set; }
    }
}
