//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_gamelogout
    {
        public int logid { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> kindid { get; set; }
        public Nullable<int> serverid { get; set; }
        public Nullable<long> gold { get; set; }
        public Nullable<long> bank { get; set; }
        public string clientip { get; set; }
        public Nullable<int> code { get; set; }
    }
}
