//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_rates
    {
        public int id { get; set; }
        public Nullable<float> rate1 { get; set; }
        public Nullable<float> rate2 { get; set; }
        public Nullable<float> rate3 { get; set; }
        public Nullable<float> rate1to2 { get; set; }
        public Nullable<float> rate1to3 { get; set; }
        public Nullable<float> rate2to3 { get; set; }
    }
}
