//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_admin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int level { get; set; }
        public int userid { get; set; }
        public int parentid { get; set; }
        public int invitecode { get; set; }
        public string phone { get; set; }
        public string real_name { get; set; }
        public float accumulated_income { get; set; }
        public float balance { get; set; }
        public Nullable<int> up_agentid { get; set; }
        public string wechat { get; set; }
        public string area { get; set; }
    }
}
